# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy .NET API to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./BoxExpress.Api/BoxExpress.Api.csproj

      - name: Build
        run: dotnet build ./BoxExpress.Api/BoxExpress.Api.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./BoxExpress.Api/BoxExpress.Api.csproj --configuration Release --no-build -o ./publish

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: <TU_APP_SERVICE_NAME>
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish

          

